[connections.snowflake]
account = "NKLYVBJ.ID53108"
user = "ABHAY1805"
password = "Deepa_0802"
role = "ACCOUNTADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive = true
