[connections.snowflake]
account = "NKLYVBJ-ID53108"
user = "abhay1805"
password = "abhay1805"
role = "ACCOUNTADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive = true
